version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prismapass
      - POSTGRES_DB=prismadb
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: