version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prismapass
      - POSTGRES_DB=prismadb
    volumes:
      - "./.data/postgresql:/var/lib/postgresql"
    restart: on-failure

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: on-failure
