name: e2e test

on: [pull_request]

jobs:
  postgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: prisma
          POSTGRES_PASSWORD: prismapass
          POSTGRES_DB: prismadb
        ports:
          - 5432/tcp
        options:  >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Apply migrations
        run: npx prisma migrate dev

      - name: run e2e test
        run: npm run test:e2e